replicaCount: 1

image:
  repository: katok747/rmq-producer
  pullPolicy: IfNotPresent
  tag: "0.1"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  rmqEndpoint: rmq-rabbitmq.rmq
  rmqQueue: MQ
  rmqUsername: admin
  rmqPassword: admin
  rmqPort: 5672
  rmqVh: /

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

serviceAccount:
  create: false
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
