apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rmq-producer.fullname" . }}
  labels:
    {{- include "rmq-producer.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "rmq-producer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "rmq-producer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rmq-producer.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RMQ_ENDPOINT
              value: "{{ .Values.env.rmqEndpoint }}"
            - name: RMQ_QUEUE
              value: "{{ .Values.env.rmqQueue }}"
            - name: RMQ_USERNAME
              value: "{{ .Values.env.rmqUsername }}"
            - name: RMQ_PASSWORD
              value: "{{ .Values.env.rmqPassword }}"
            - name: RMQ_PORT
              value: "{{ .Values.env.rmqPort }}"
            - name: RMQ_VH
              value: "{{ .Values.env.rmqVh }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}